/* CREATE DATABASE moved to database-setup.sh */

create table IncomeCategory
(
	id bigint generated by default as identity primary key,
	name character(30) not null unique
);

create table User_
(
	id bigint generated by default as identity primary key,
	login character(15) not null unique,
	password character(40) not null
);

create table Income
(
	id bigint generated by default as identity primary key,
	name character(30) not null,
	userId bigint not null references User_(id),
	amount money not null,
	categoryId bigint not null references IncomeCategory(id),
	addTime timestamp not null,
	expirationTime timestamp
);

create table ListState
(
	id bigint generated by default as identity primary key,
	name character(30) not null unique 
);

create table List
(
	id bigint generated by default as identity primary key,
	userId bigint not null references User_(id),
	name character(30) not null,
	stateId bigint not null references ListState(id)
);

create table Coownership
(
	userId bigint references User_(id),
	listId bigint references List(id),
	primary key(userId, listId)
);

create table ProductCategory
(
	id bigint generated by default as identity primary key,
	name character(30) not null unique 
);

create table Product
(
	id bigint generated by default as identity primary key,
	listId bigint not null references List(id),
	categoryId bigint not null references ProductCategory(id),
	name character(30) not null,
	price money not null,
	amount bigint not null,
	productPriority integer not null,
	isBought boolean not null,
	addDate timestamp not null,
	purchaseDate timestamp,
	buyUntilDate timestamp
);

