INSERT INTO public.productcategory
	("name", userId)
VALUES
	('food', 1),
	('health', 1),
	('entertainment', 1),
	('clothes', 1),
	('sports', 1),
	('transport', 1),
	('tech', 1),
	('other', 1),
	
	('food', 2),
	('health', 2),
	('entertainment', 2),
	('clothes', 2),
	('sports', 2),
	('transport', 2),
	('tech', 2),
	('other', 2),
	
	('food', 3),
	('health', 3),
	('entertainment', 3),
	('clothes', 3),
	('sports', 3),
	('transport', 3),
	('tech', 3),
	('other', 3),
	
	('food', 4),
	('health', 4),
	('entertainment', 4),
	('clothes', 4),
	('sports', 4),
	('transport', 4),
	('tech', 4),
	('other', 4),
	
	('food', 5),
	('health', 5),
	('entertainment', 5),
	('clothes', 5),
	('sports', 5),
	('transport', 5),
	('tech', 5),
	('other', 5),
	
	('food', 6),
	('health', 6),
	('entertainment', 6),
	('clothes', 6),
	('sports', 6),
	('transport', 6),
	('tech', 6),
	('other', 6);

