#include <QJsonArray>

#include "GetProductsForPeriodicProductHandler.h"
#include "Net/Parsing.h"
#include "Server/Error.h"
#include "Server/Utils.h"
#include "../Common.h"
#include "Logger/ScopedLogger.h"
#include "../libdal/Exceptions/NonexistentResource.h"
#include "Utils.h"

GetProductsForPeriodicProductHandler::GetProductsForPeriodicProductHandler()
{
}

Net::Response GetProductsForPeriodicProductHandler::AuthHandle(const Net::Request& request)
{
	SCOPED_LOGGER;
	Q_UNUSED(request);

	//auto list_id = std::get<long long>(m_params.Get(Params::LIST_ID));
	auto periodic_id = std::get<long long>(m_params.Get(Params::PERIODIC_PRODUCT_ID));

	if (!m_facade->CanUserEditPeriodicProduct(request.uid, periodic_id)){
		return FormErrorResponse(
			NetError::Status::HTTP_FORBIDDEN,
			"User with id \"" + std::to_string(request.uid) +
			"\" can't get products generated by periodic product with id \"" + std::to_string(periodic_id) + "\"");;
	}

	std::vector<db::Product> db_products;
	try
	{
		db_products = m_facade->GetProductsForPeriodicProduct(periodic_id);
	}
	catch (const db::NonexistentResource& ex) {
		return FormErrorResponse(
			NetError::Status::HTTP_NOT_FOUND,
			"Periodic product with id = \"" + std::to_string(periodic_id) + "\" not found");
	}

	std::vector<Product> products;
	for (const db::Product& db_product : db_products) {
		auto category = m_facade->GetProductCategoryById(db_product.category_id);
		if (!category.has_value())
		{
			throw InternalError(std::string("No product category with id:") + std::to_string(db_product.category_id));
		}
		auto product = ToNetProduct(db_product, category.value());
		products.push_back(product);
	}

	return FormJSONResponse(m_formatter.Format(products));
}
